//file:noinspection GrDeprecatedAPIUsage
plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.143'
}

def modId = providers.gradleProperty("mod_id").get()

version = providers.gradleProperty("mod_version").get()
group = providers.gradleProperty("mod_group_id").get()

base {
    archivesName.set(modId)
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

repositories {
    mavenLocal()
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name = "Jared Maven (JEI)"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}

dependencies {
    def minecraftVersion = providers.gradleProperty("minecraft_version").get()
    def jadeVersion = providers.gradleProperty("jade_version").get()
    def jeiVersion = providers.gradleProperty("jei_version").get()

    compileOnly "maven.modrinth:jade:${jadeVersion}"
    compileOnly "mezz.jei:jei-${minecraftVersion}-neoforge-api:${jeiVersion}"

    runtimeOnly "maven.modrinth:jade:${jadeVersion}"
    runtimeOnly "mezz.jei:jei-${minecraftVersion}-neoforge:${jeiVersion}"
}

def mainSourceSet = sourceSets.named("main")

neoForge {
    version = providers.gradleProperty("neo_version").get()

    parchment {
        mappingsVersion = providers.gradleProperty("parchment_mappings_version").get()
        minecraftVersion = providers.gradleProperty("parchment_minecraft_version").get()
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', modId
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', modId
        }

        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', modId
        }

        data {
            data()
            programArgument '--mod'
            programArgument modId
            programArgument '--all'
            programArgument '--output'
            programArgument file('src/generated/resources/').absolutePath
            programArgument '--existing'
            programArgument file('src/main/resources/').absolutePath
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        register(modId) { mod ->
            mod.sourceSet(mainSourceSet.get())
        }
    }
}

def generateModMetadata = tasks.register("generateModMetadata", ProcessResources) { task ->
    var replaceProperties = project.properties.findAll { key, val -> val instanceof String }
    replaceProperties.put("mod_id", modId)

    task.inputs.properties(replaceProperties)
    task.expand(replaceProperties)
    task.from("src/main/templates")
    task.into("build/generated/sources/modMetadata")
}

sourceSets.main {
    resources {
        srcDir('src/generated/resources')
        srcDir(generateModMetadata)
        exclude("**/*.bbmodel")
        exclude("**/.cache/**")
    }
}

neoForge.ideSyncTask(generateModMetadata)

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) { pub ->
            pub.from components['java'] as SoftwareComponent
        }
    }
    repositories {
        maven {
            url = layout.buildDirectory.dir("repo")
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
