plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.143'
}

def modId = providers.gradleProperty("mod_id").get()

version = providers.gradleProperty("mod_version").get()
group = providers.gradleProperty("mod_group_id").get()

base {
    archivesName.set(modId)
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

repositories {
    mavenLocal()
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name = "Jared Maven (JEI)"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}

dependencies {
    def minecraftVersion = providers.gradleProperty("minecraft_version").get()
    def jadeVersion = providers.gradleProperty("jade_version").get()
    def jeiVersion = providers.gradleProperty("jei_version").get()

    compileOnly "maven.modrinth:jade:${jadeVersion}"
    compileOnly "mezz.jei:jei-${minecraftVersion}-neoforge-api:${jeiVersion}"

    runtimeOnly "maven.modrinth:jade:${jadeVersion}"
    runtimeOnly "mezz.jei:jei-${minecraftVersion}-neoforge:${jeiVersion}"
}

def mainSourceSet = sourceSets.named("main")

neoForge {
    version = providers.gradleProperty("neo_version").get()

    parchment {
        mappingsVersion = providers.gradleProperty("parchment_mappings_version").get()
        minecraftVersion = providers.gradleProperty("parchment_minecraft_version").get()
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', modId
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', modId
        }

        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', modId
        }

        data {
            data()
            programArgument '--mod'
            programArgument modId
            programArgument '--all'
            programArgument '--output'
            programArgument file('src/generated/resources/').absolutePath
            programArgument '--existing'
            programArgument file('src/main/resources/').absolutePath
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        register(modId) { mod ->
            mod.sourceSet(mainSourceSet.get())
        }
    }
}

def generateModMetadata = tasks.register("generateModMetadata", ProcessResources) { task ->
    var replaceProperties = [
            minecraft_version      : providers.gradleProperty("minecraft_version").get(),
            minecraft_version_range: providers.gradleProperty("minecraft_version_range").get(),
            neo_version            : providers.gradleProperty("neo_version").get(),
            neo_version_range      : providers.gradleProperty("neo_version_range").get(),
            loader_version_range   : providers.gradleProperty("loader_version_range").get(),
            mod_id                 : modId,
            mod_name               : providers.gradleProperty("mod_name").get(),
            mod_license            : providers.gradleProperty("mod_license").get(),
            mod_version            : providers.gradleProperty("mod_version").get(),
            mod_authors            : providers.gradleProperty("mod_authors").get(),
            mod_description        : providers.gradleProperty("mod_description").orElse("").get(),
            mod_banner             : providers.gradleProperty("mod_banner").orElse("").get(),

            jade_mod_id            : providers.gradleProperty("jade_mod_id").orElse("").get(),
            jade_type              : providers.gradleProperty("jade_type").orElse("").get(),
            jade_version_range     : providers.gradleProperty("jade_version_range").orElse("").get(),
            jade_ordering          : providers.gradleProperty("jade_ordering").orElse("").get(),
            jade_side              : providers.gradleProperty("jade_side").orElse("").get(),

            jei_mod_id             : providers.gradleProperty("jei_mod_id").orElse("").get(),
            jei_type               : providers.gradleProperty("jei_type").orElse("").get(),
            jei_version_range      : providers.gradleProperty("jei_version_range").orElse("").get(),
            jei_ordering           : providers.gradleProperty("jei_ordering").orElse("").get(),
            jei_side               : providers.gradleProperty("jei_side").orElse("").get()
    ]

    task.inputs.properties(replaceProperties)
    task.expand(replaceProperties)
    task.from("src/main/templates")
    task.into("build/generated/sources/modMetadata")
}

sourceSets.main {
    resources {
        srcDir('src/generated/resources')
        srcDir(generateModMetadata)
        exclude("**/*.bbmodel")
        exclude("**/ .cache/**")
    }
}

neoForge.ideSyncTask(generateModMetadata)

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) { pub ->
            pub.from components['java'] as SoftwareComponent
        }
    }
    repositories {
        maven {
            url = layout.buildDirectory.dir("repo")
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
