org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.2)

neo_version=21.1.235
neo_version_range=[21,)
loader_version_range=[4,)

parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20

## Mod Properties
mod_id=nerdsoftkitchen
mod_name=NerdSoft Kitchen
mod_license=CC-BY-NC-SA-4.0
mod_version=0.1.1+1.21(.1)
mod_group_id=com.nerdsoft.mods
mod_authors=Bichal & Hugo
mod_description=A fresh, lightweight cooking and farming expansion adding wild crops, pole-grown tomatoes, grill workstations, and delicious new recipes to Minecraft.
mod_side=BOTH
mod_banner=banner.png

## Dependencies
jade_mod_id=jade
jade_type=optional
jade_version=15.10.5+neoforge
jade_version_range=[15.0,)
jade_ordering=AFTER
jade_side=CLIENT

jei_mod_id=jei
jei_type=optional
jei_version=19.10.0.126
jei_version_range=[19.0,)
jei_ordering=AFTER
jei_side=CLIENT