modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${mod_issues}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
logoFile = "${mod_banner}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "${mod_side}"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "${mod_side}"

[[dependencies."${mod_id}"]]
modId = "${jade_mod_id}"
type = "${jade_type}"
versionRange = "${jade_version_range}"
ordering = "${jade_ordering}"
side = "${jade_side}"

#? if <1.21.2 {
[[dependencies."${mod_id}"]]
modId = "${jei_mod_id}"
type = "${jei_type}"
versionRange = "${jei_version_range}"
ordering = "${jei_ordering}"
side = "${jei_side}"
#?}
