minecraft.version=1.21.3
minecraft.version.range=[1.21.2,1.21.4)

neo.version=21.3.97
neo.version.range=[21.2,21.4)

loader.version.range=[1,)

parchment.minecraft.version=1.21.3
parchment.mappings.version=2024.12.07

# JEI its not compatible with 1.21.2 and .3
deps.jei.version=0
deps.jei.version.range=[0,)

deps.jade.version=16.0.1+neoforge
deps.jade.version.range=[16,17)